this is my .conf,
# List of words to be filtered from text files
FILTER_WORDS=ducati,ferrari,mu,chelsea,prx,onic,sisop

# Base name of the restricted file
SECRET_FILE_BASENAME=secret

# Access time window for secret files (24-hour format)
ACCESS_START=08:00
ACCESS_END=18:00
